reference: "resources/reference-genome/GRCh37/hs37d5.fa"
# NOTE: indexes required by aligners must be present in same directory as reference.

aligners: 
# key = aligner, value = path to aligner (if not using conda/apptainer)
  bwa-mem2: ""
  novoalign: "/export/home/jeffrey/.local/bin/novocraft/novoalign"

novoindex: "/export/home/jeffrey/.local/bin/novocraft/novoindex"

samples:
# key = sample ID, value = list of paths to FASTQ files
  HG002:
    - "resources/samples/HG002/HG002_HiSeq30x_subsampled_R1.fastq.gz"
    - "resources/samples/HG002/HG002_HiSeq30x_subsampled_R2.fastq.gz"

callers:
# Note: I could not get the last 3 to work :C
  - "delly"
  - "dysgu"
  - "insurveyor"
  - "manta"
  # - "lumpy"
  # - "tiddit"
  # - "wham"

truth_sets:
# Make sure they are bgzipped and tabix-indexed VCF files.
# Must be renamed to end with ".ALL.vcf.gz".
  HG002: 
    "resources/sv-benchmarks/HG002/HG002_SVs_Tier1_v0.6.ALL.vcf.gz"

truth_set_svtypes:
  - "ALL"
  - "DEL"
  - "INS"