reference: "/export/home/jeffrey/Documents/sv-benchmarking/resources/reference-genome/GRCh37/hs37d5.fa"

aligners: 
  bwa-mem2: ""
  novoalign: "/export/home/jeffrey/.local/bin/novocraft/novoalign"

samples:
  HG002:
    - "/export/home/jeffrey/Documents/sv-benchmarking/resources/samples/HG002/HG002_HiSeq30x_subsampled_R1.fastq.gz"
    - "/export/home/jeffrey/Documents/sv-benchmarking/resources/samples/HG002/HG002_HiSeq30x_subsampled_R2.fastq.gz"

callers:
  - "delly"
  # - "dysgu"
  - "lumpy"
  - "manta"
  # - "tiddit"
  - "wham"

truth_sets:
  HG002: 
    "/export/home/jeffrey/Documents/sv-benchmarking/resources/sv-benchmarks/HG002/HG002_SVs_Tier1_v0.6.vcf.gz"